name: Test Coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ci-secret-key-at-least-thirty-two-bytes
      GCP_PRIMARY_PROJECT_ID: ci-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nest_db
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Restore Cache
        uses: actions/cache@v6
        with:
          path: |
            node_modules
            ~/.npm
          key: node-v1-${{ runner.os }}-${{ hashFiles('package-lock.json', 'prisma/schema.prisma') }}

      - name: Run Tests & Coverage
        run: npm run test:cov
