name: Unit Tests

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      GCP_PRIMARY_PROJECT_ID: ci-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/nest_db
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: node-v1-${{ runner.os }}-${{ hashFiles('package-lock.json', 'prisma/schema.prisma') }}

      - name: Run Unit Tests
        run: npm run test
